theme = "adwaita-dark"

[editor]
bufferline = "multiple"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

